const express=require('express');const cors=require('cors');const jwt=require('jsonwebtoken');const path=require('path');const crypto=require('crypto');const twilio=require('twilio');const {Pool}=require('pg');const multer=require('multer');const helmet=require('helmet');const rateLimit=require('express-rate-limit');const webpush=require('web-push');const QRCode=require('qrcode');require('dotenv').config();
const app=express();const PORT=process.env.PORT||3000;const JWT_SECRET=process.env.JWT_SECRET;const OWNER_NAME=process.env.OWNER_NAME||'Jessica';
// For hosted demos, allow startup without a configured JWT secret. Set JWT_SECRET in Render for persistent production sessions.
const SIGNING_SECRET=JWT_SECRET||crypto.randomBytes(32).toString('hex');
if(!JWT_SECRET) console.warn('WARNING: JWT_SECRET is not configured. A temporary signing secret is being used; sessions reset after restart.');
app.set('trust proxy',1);
if(process.env.NODE_ENV==='production'){
  app.use((req,res,next)=>{
    const proto=req.get('x-forwarded-proto')||req.protocol;
    if(proto!=='https' && req.path!=='/api/health') return res.redirect(308,'https://'+req.get('host')+req.originalUrl);
    next();
  });
}
const allowedOrigins=(process.env.ALLOWED_ORIGINS||'').split(',').map(x=>x.trim()).filter(Boolean);
app.use(helmet({contentSecurityPolicy:false,referrerPolicy:{policy:'no-referrer'},crossOriginEmbedderPolicy:false}));
app.use(cors({origin:(origin,cb)=>{if(!origin||allowedOrigins.length===0||allowedOrigins.includes(origin))return cb(null,true);cb(new Error('Origin not allowed'));},methods:['GET','POST','PATCH','PUT','DELETE','OPTIONS'],allowedHeaders:['Content-Type','Authorization'],credentials:false}));
app.use(express.json({limit:'1mb'}));app.use(express.urlencoded({extended:false,limit:'1mb'}));
// Simple honeypot spam protection for public forms/APIs. Legitimate clients never send this field.
app.use('/api/',(req,res,next)=>{
  if(['POST','PUT','PATCH'].includes(req.method) && req.body && String(req.body.website||'').trim()) return res.status(400).json({error:'Request rejected'});
  next();
});
const apiLimiter=rateLimit({windowMs:60*1000,max:120,standardHeaders:true,legacyHeaders:false,message:{error:'Too many requests'}});
app.use('/api/',apiLimiter);
app.get('/robots.txt',(req,res)=>{const base=(process.env.APP_URL||`${req.protocol}://${req.get('host')}`).replace(/\/$/,'');res.type('text/plain').send(`User-agent: *\nAllow: /\nDisallow: /admin\nDisallow: /admin-request.html\nDisallow: /vendor\nDisallow: /hotel\nDisallow: /rider\nDisallow: /api/\nSitemap: ${base}/sitemap.xml\n`) });
app.get('/sitemap.xml',(req,res)=>{const base=(process.env.APP_URL||`${req.protocol}://${req.get('host')}`).replace(/\/$/,'');res.type('application/xml').send(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>${base}/</loc></url><url><loc>${base}/privacy</loc></url><url><loc>${base}/terms</loc></url><url><loc>${base}/refunds</loc></url><url><loc>${base}/cookies</loc></url></urlset>`)});
app.use(express.static(path.join(__dirname,'public'),{dotfiles:'deny',index:false}));
const authLimiter=rateLimit({windowMs:15*60*1000,max:20,standardHeaders:true,legacyHeaders:false});
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:6*1024*1024}});
const pool=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_SSL==='false'?false:{rejectUnauthorized:false}}):null;
const memory={users:new Map(),orders:new Map(),bookings:new Map(),payments:new Map(),documents:new Map(),tracking:new Map(),push:new Map(),feedback:new Map(),audit:[],businesses:new Map(),catalog:new Map(),applications:new Map(),riders:new Map(),adminRequests:new Map(),referrals:new Map(),referralCodes:new Map()};
async function q(text,params=[]){if(!pool)throw new Error('DATABASE_NOT_CONFIGURED');return (await pool.query(text,params)).rows}
async function initDb(){
 if(!pool)return;
 await pool.query(`
  create extension if not exists pgcrypto;
  create table if not exists users(id uuid primary key default gen_random_uuid(),phone text unique not null,email text,full_name text,role text default 'customer',verified boolean default false,status text default 'active',created_at timestamptz default now(),updated_at timestamptz default now());
  create table if not exists role_applications(id uuid primary key default gen_random_uuid(),phone text not null references users(phone) on delete cascade,requested_role text not null,business_name text,notes text,status text not null default 'pending',created_at timestamptz default now(),reviewed_at timestamptz);
  create table if not exists orders(id text primary key,customer_phone text not null,vendor text,items jsonb default '[]',total numeric default 0,status text,created_at timestamptz default now(),updated_at timestamptz default now(),rider_phone text,pickup_code text default '4821',delivery_pin text default '7392',delivery_lat double precision,delivery_lng double precision,delivery_address text);
  create table if not exists order_feedback(id uuid primary key default gen_random_uuid(),order_id text unique not null,customer_phone text not null,rider_phone text,rating integer not null check(rating between 1 and 5),comment text default '',created_at timestamptz default now());
  create table if not exists bookings(id text primary key,customer_phone text not null,hotel text,room text,total numeric default 0,status text,created_at timestamptz default now(),updated_at timestamptz default now());
  create table if not exists payments(tx_ref text primary key,user_phone text,entity_type text,entity_id text,amount numeric,currency text default 'GHS',status text default 'pending',provider text default 'flutterwave',transaction_id text,created_at timestamptz default now());
  create table if not exists tracking_points(id bigserial primary key,order_id text,lat double precision,lng double precision,accuracy double precision,created_at timestamptz default now());
  create table if not exists documents(id uuid primary key default gen_random_uuid(),user_phone text,doc_type text,file_url text,status text default 'pending',created_at timestamptz default now());
  create table if not exists push_subscriptions(id uuid primary key default gen_random_uuid(),user_phone text,endpoint text unique,subscription jsonb,created_at timestamptz default now());
  create table if not exists audit_logs(id bigserial primary key,actor text,action text,entity_type text,entity_id text,meta jsonb,created_at timestamptz default now());
 `);
 await pool.query(`
  create table if not exists business_profiles(
   id uuid primary key default gen_random_uuid(), owner_phone text not null references users(phone) on delete cascade,
   kind text not null check(kind in ('vendor','hotel')), business_name text not null, business_phone text, email text,
   address text, description text, ghana_card_name text, ghana_card_number text, registration_number text,
   status text not null default 'pending' check(status in ('pending','approved','rejected')),
   metadata jsonb not null default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
  create unique index if not exists business_owner_kind_idx on business_profiles(owner_phone,kind);
  create table if not exists catalog_items(
   id uuid primary key default gen_random_uuid(), business_id uuid not null references business_profiles(id) on delete cascade,
   name text not null, category text, price numeric(12,2) not null default 0, description text default '', active boolean not null default true,
   created_at timestamptz default now(), updated_at timestamptz default now());
  create index if not exists catalog_search_idx on catalog_items(lower(name),lower(category));
  create table if not exists rider_profiles(
   phone text primary key references users(phone) on delete cascade, full_name text, ghana_card_name text, ghana_card_number text,
   license_number text, vehicle_type text, plate_number text, address text, emergency_phone text,
   status text not null default 'pending' check(status in ('pending','approved','rejected')),
   metadata jsonb not null default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
  create table if not exists admin_access_requests(
   id uuid primary key default gen_random_uuid(), phone text not null references users(phone) on delete cascade, full_name text,
   ghana_card_number text, reason text, status text not null default 'pending' check(status in ('pending','approved','rejected')),
   created_at timestamptz default now(), reviewed_at timestamptz);
  create index if not exists role_apps_status_idx on role_applications(status,created_at);
  create index if not exists admin_requests_status_idx on admin_access_requests(status,created_at);
  create table if not exists referral_codes(
   code text primary key, phone text unique not null references users(phone) on delete cascade, created_at timestamptz default now()
  );
  create table if not exists referrals(
   id uuid primary key default gen_random_uuid(), inviter_phone text not null references users(phone) on delete cascade,
   invitee_phone text not null unique references users(phone) on delete cascade, referral_code text not null references referral_codes(code),
   status text not null default 'joined' check(status in ('joined','qualified')), created_at timestamptz default now(), qualified_at timestamptz
  );
  create unique index if not exists referrals_code_idx on referrals(referral_code);
  create index if not exists referrals_inviter_idx on referrals(inviter_phone,created_at desc);
 `);
}
function normalizePhone(p){return String(p||'').replace(/[\s()-]/g,'')}function validE164(p){return /^\+[1-9]\d{7,14}$/.test(p)}
const twilioConfigured=!!(process.env.TWILIO_ACCOUNT_SID&&process.env.TWILIO_AUTH_TOKEN&&process.env.TWILIO_VERIFY_SERVICE_SID);const twilioClient=twilioConfigured?twilio(process.env.TWILIO_ACCOUNT_SID,process.env.TWILIO_AUTH_TOKEN):null;
async function sendOtp(phone){if(twilioConfigured){const v=await twilioClient.verify.v2.services(process.env.TWILIO_VERIFY_SERVICE_SID).verifications.create({to:phone,channel:'sms'});return{provider:'twilio',status:v.status}}if(process.env.DEV_OTP==='true'){global.devOtps=global.devOtps||new Map();const code=String(Math.floor(100000+Math.random()*900000));global.devOtps.set(phone,{code,expires:Date.now()+300000});console.log('[DEV OTP]',phone,code);return{provider:'development',status:'pending',devOtp:code}}throw Object.assign(new Error('OTP service not configured'),{statusCode:503})}
async function verifyOtp(phone,code){if(twilioConfigured)return twilioClient.verify.v2.services(process.env.TWILIO_VERIFY_SERVICE_SID).verificationChecks.create({to:phone,code});const r=global.devOtps?.get(phone);if(!r||Date.now()>r.expires)return{status:'canceled'};global.devOtps.delete(phone);return{status:r.code===code?'approved':'pending'}}
async function getUser(phone){if(pool){const r=await q('select * from users where phone=$1',[phone]);return r[0]}return memory.users.get(phone)}
function configuredRole(phone){const admins=(process.env.ADMIN_PHONES||'').split(',').map(normalizePhone).filter(Boolean);return admins.includes(phone)?'admin':'customer'}
async function getRoleProfile(phone,kind){if(pool){return (await q('select * from business_profiles where owner_phone=$1 and kind=$2 order by created_at desc limit 1',[phone,kind]))[0]||null}return [...memory.businesses.values()].find(x=>x.owner_phone===phone&&x.kind===kind)||null}
function cleanText(v,n=160){return String(v||'').trim().slice(0,n)}
function publicSearchSeed(){return [
{id:'seed-food-1',type:'food',icon:'🍗',name:'Jollof + Chicken',vendor:'Obuasi Kitchen',price:38,tags:'jollof rice chicken food ghana meal lunch dinner'},
{id:'seed-food-2',type:'food',icon:'🍕',name:'Pizza',vendor:'Pizza Hub Obuasi',price:55,tags:'pizza food cheese pepperoni fast food'},
{id:'seed-food-3',type:'food',icon:'🥘',name:'Local Meal',vendor:'Ashanti Chop Bar',price:32,tags:'local food fufu banku soup ampesi chop bar'},
{id:'seed-food-4',type:'food',icon:'🍰',name:'Pastry',vendor:'Sweet Crumbs',price:18,tags:'bakery pastry cake bread dessert'},
{id:'seed-food-5',type:'food',icon:'🍔',name:'Burger',vendor:'Obuasi Kitchen',price:42,tags:'burger food fast food beef chicken'},
{id:'seed-food-6',type:'food',icon:'🍟',name:'Chicken & Chips',vendor:'Obuasi Kitchen',price:45,tags:'chicken chips fries food'},
{id:'seed-food-7',type:'food',icon:'🥤',name:'Soft Drink',vendor:'Sweet Crumbs',price:10,tags:'drink drinks soda beverage'},
{id:'seed-hotel-1',type:'hotel',icon:'🏨',name:'Executive Room',vendor:'Obuasi Royal Hotel',price:450,tags:'hotel room stay accommodation wifi breakfast'},
{id:'seed-hotel-2',type:'hotel',icon:'🏨',name:'Comfort Room',vendor:'Golden View Lodge',price:320,tags:'hotel room stay accommodation parking lodge'}
]}
async function searchCatalog(raw,type){
 const needle=cleanText(raw,120).toLowerCase();const words=needle.split(/\s+/).filter(Boolean);const matches=(x)=>{if(type&&type!=='all'&&x.type!==type)return false;if(!needle)return true;const text=[x.name,x.vendor,x.tags,x.type].join(' ').toLowerCase();return text.includes(needle)||words.every(w=>text.includes(w))};
 const seeds=publicSearchSeed();let out=seeds.filter(matches);
 if(pool){const like=needle||'';const biz=await q(`select b.id,b.kind,b.business_name,b.address,b.description,c.id as item_id,c.name,c.category,c.price,c.description as item_description from business_profiles b left join catalog_items c on c.business_id=b.id and c.active=true where b.status='approved' and ($1='' or lower(b.business_name||'') like '%'||lower($1)||'%' or lower(coalesce(b.description,'')) like '%'||lower($1)||'%' or lower(coalesce(c.name,'')) like '%'||lower($1)||'%' or lower(coalesce(c.category,'')) like '%'||lower($1)||'%') order by b.created_at desc limit 100`,[like]);for(const x of biz){const isHotel=x.kind==='hotel';if(type&&type!=='all'&&x.kind!==type)continue;const item={id:x.item_id||x.id,type:x.kind,icon:isHotel?'🏨':'🍽️',name:x.name||(isHotel?x.business_name:'Menu'),vendor:x.business_name,price:Number(x.price||0),tags:[x.category,x.address,x.description,x.item_description].filter(Boolean).join(' '),businessId:x.id};if(matches(item))out.push(item)}}
 return out;
}
function referralCodeFor(phone){return 'OBG-'+crypto.createHash('sha256').update(String(phone)+'|OBUASIGO-REFERRAL').digest('hex').slice(0,8).toUpperCase()}
async function ensureReferralCode(phone){
 const code=referralCodeFor(phone);
 if(pool) await q('insert into referral_codes(code,phone) values($1,$2) on conflict(phone) do nothing',[code,phone]);
 else memory.referralCodes.set(phone,code);
 return code;
}
async function getReferralStats(phone){
 const code=await ensureReferralCode(phone);
 if(pool){
  const counts=(await q(`select count(*)::int as total, count(*) filter(where status='qualified')::int as qualified from referrals where inviter_phone=$1`,[phone]))[0];
  return {code,total:counts?.total||0,qualified:counts?.qualified||0};
 }
 const rows=[...memory.referrals.values()].filter(x=>x.inviter_phone===phone);
 return {code,total:rows.length,qualified:rows.filter(x=>x.status==='qualified').length};
}
async function attachReferral(inviteePhone,code){
 const c=String(code||'').trim().toUpperCase(); if(!/^OBG-[A-F0-9]{8}$/.test(c)) return false;
 if(pool){
  const found=(await q('select phone from referral_codes where code=$1',[c]))[0];
  if(!found||found.phone===inviteePhone)return false;
  const exists=(await q('select id from referrals where invitee_phone=$1',[inviteePhone]))[0];
  if(exists)return false;
  await q("insert into referrals(inviter_phone,invitee_phone,referral_code,status) values($1,$2,$3,'joined') on conflict(invitee_phone) do nothing",[found.phone,inviteePhone,c]);
  await audit(inviteePhone,'referral.joined','referral',inviteePhone,{inviter:found.phone});
  return true;
 }
 const found=[...memory.referralCodes.entries()].find(([phone,v])=>v===c&&phone!==inviteePhone)?.[0];
 if(!found||memory.referrals.has(inviteePhone))return false;
 memory.referrals.set(inviteePhone,{inviter_phone:found,invitee_phone:inviteePhone,referral_code:c,status:'joined',created_at:new Date().toISOString()});
 return true;
}
async function qualifyReferralForUser(phone){
 if(pool) await q("update referrals set status='qualified',qualified_at=now() where invitee_phone=$1 and status='joined'",[phone]);
 else {const r=memory.referrals.get(phone);if(r&&r.status==='joined'){r.status='qualified';r.qualified_at=new Date().toISOString()}}
}
async function upsertUser(phone,referralCode){const role=configuredRole(phone);let existed=!!(await getUser(phone));let user;if(pool){const r=await q(`insert into users(phone,role,verified) values($1,$2,true) on conflict(phone) do update set verified=true,role=case when $2='admin' then 'admin' else users.role end returning *`,[phone,role]);user=r[0]}else{let u=memory.users.get(phone)||{phone,role,verified:true,createdAt:new Date().toISOString()};u.verified=true;if(role==='admin')u.role='admin';memory.users.set(phone,u);user=u}await ensureReferralCode(phone);if(!existed&&referralCode&&user.role==='customer')await attachReferral(phone,referralCode);return user}
function auth(req,res,next){try{req.user=jwt.verify((req.headers.authorization||'').replace(/^Bearer\s+/,'').trim(),SIGNING_SECRET);next()}catch{return res.status(401).json({error:'Authentication required'})}}
function admin(req,res,next){if(!['admin','superadmin'].includes(req.user.role))return res.status(403).json({error:'Admin access required'});next()}
function roles(...allowed){return (req,res,next)=>allowed.includes(req.user.role)?next():res.status(403).json({error:'Insufficient permissions'})}
async function audit(actor,action,type,id,meta={}){if(pool)await q('insert into audit_logs(actor,action,entity_type,entity_id,meta) values($1,$2,$3,$4,$5)',[actor,action,type,id,JSON.stringify(meta)]);else memory.audit.push({actor,action,type,id,meta,at:new Date().toISOString()})}
app.get('/api/health',async(req,res)=>res.json({ok:true,owner:OWNER_NAME,service:'ObuasiGo API',database:pool?'postgres':'memory-dev',otpProvider:twilioConfigured?'twilio-verify':process.env.DEV_OTP==='true'?'development':'not-configured',payments:process.env.FLW_SECRET_KEY?'flutterwave':'not-configured',maps:'browser-geolocation+leaflet',push:process.env.VAPID_PUBLIC_KEY?'web-push':'not-configured',time:new Date().toISOString()}));
app.post('/api/auth/request-otp',authLimiter,async(req,res)=>{const phone=normalizePhone(req.body.phone);if(!validE164(phone))return res.status(400).json({error:'Use international format, e.g. +233241234567'});try{const r=await sendOtp(phone);res.json({ok:true,message:'OTP sent',provider:r.provider,...(r.devOtp?{devOtp:r.devOtp}:{})})}catch(e){res.status(e.statusCode||502).json({error:'Could not send OTP'})}});
app.post('/api/auth/verify-otp',authLimiter,async(req,res)=>{const phone=normalizePhone(req.body.phone),code=String(req.body.code||'').trim(),referralCode=String(req.body.referralCode||'').trim();if(!validE164(phone)||!/^[0-9]{4,10}$/.test(code))return res.status(400).json({error:'Invalid phone or OTP'});try{const c=await verifyOtp(phone,code);if(c.status!=='approved')return res.status(400).json({error:'Incorrect or expired OTP'});const user=await upsertUser(phone,referralCode);const token=jwt.sign({phone:user.phone,role:user.role||'customer',verified:true},SIGNING_SECRET,{expiresIn:'7d'});res.json({ok:true,token,user})}catch(e){res.status(502).json({error:'Could not verify OTP'})}});
app.get('/api/me',auth,async(req,res)=>{const u=await getUser(req.user.phone)||req.user;let profile=null;if(u.role==='vendor')profile=await getRoleProfile(req.user.phone,'vendor');if(u.role==='hotel')profile=await getRoleProfile(req.user.phone,'hotel');if(u.role==='rider'&&pool)profile=(await q('select * from rider_profiles where phone=$1',[req.user.phone]))[0]||null;res.json({user:u,profile})});
app.post('/api/auth/refresh',auth,async(req,res)=>{const user=await getUser(req.user.phone);if(!user)return res.status(404).json({error:'User not found'});const token=jwt.sign({phone:user.phone,role:user.role||'customer',verified:!!user.verified},SIGNING_SECRET,{expiresIn:'7d'});res.json({ok:true,token,user})});
function makeId(p){return p+Math.floor(10000+Math.random()*90000)}
app.get('/api/referrals/me',auth,async(req,res)=>{if(req.user.role!=='customer')return res.status(403).json({error:'Referral program is available to customer accounts'});const stats=await getReferralStats(req.user.phone);const base=process.env.APP_URL||`${req.protocol}://${req.get('host')}`;const link=`${base.replace(/\/$/,'')}/?ref=${encodeURIComponent(stats.code)}`;const qrData=await QRCode.toDataURL(link,{width:420,margin:2});res.json({ok:true,...stats,link,qrData,message:'Join me on ObuasiGo — food, hotels and delivery in one app.'})});
app.post('/api/referrals/claim',auth,async(req,res)=>{if(req.user.role!=='customer')return res.status(403).json({error:'Referral program is available to customer accounts'});const ok=await attachReferral(req.user.phone,req.body.referralCode);res.json({ok,claimed:ok,message:ok?'Referral linked successfully':'Referral code is invalid, already used, or belongs to this account'});});
app.post('/api/orders',auth,roles('customer'),async(req,res)=>{const id=makeId('OBU-'),lat=Number(req.body.delivery_lat),lng=Number(req.body.delivery_lng),o={id,customer_phone:req.user.phone,vendor:req.body.vendor||'Obuasi Kitchen',items:req.body.items||[],total:Number(req.body.total||0),status:'PAYMENT PENDING',created_at:new Date().toISOString(),pickup_code:'4821',delivery_pin:'7392',delivery_lat:Number.isFinite(lat)?lat:null,delivery_lng:Number.isFinite(lng)?lng:null,delivery_address:String(req.body.delivery_address||'').slice(0,240)};if(pool){await q('insert into orders(id,customer_phone,vendor,items,total,status,pickup_code,delivery_pin,delivery_lat,delivery_lng,delivery_address) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)',[o.id,o.customer_phone,o.vendor,JSON.stringify(o.items),o.total,o.status,o.pickup_code,o.delivery_pin,o.delivery_lat,o.delivery_lng,o.delivery_address]);}else memory.orders.set(id,o);await audit(req.user.phone,'order.created','order',id,{total:o.total});res.status(201).json(o)});
app.get('/api/orders',auth,async(req,res)=>{if(pool)return res.json(await q('select * from orders where customer_phone=$1 order by created_at desc',[req.user.phone]));res.json([...memory.orders.values()].filter(x=>x.customer_phone===req.user.phone))});
app.patch('/api/orders/:id/status',auth,async(req,res)=>{const s=String(req.body.status||'').slice(0,40);const allowed=['PAYMENT PENDING','Order created','Payment confirmed','Restaurant accepted','Preparing','Food ready','Rider assigned','Rider accepted','Rider arrived','Food picked up','Going to customer','Arrived at customer','Customer PIN verified','Completed'];if(!allowed.includes(s))return res.status(400).json({error:'Invalid order status'});if(pool){const existing=(await q('select * from orders where id=$1',[req.params.id]))[0];if(!existing)return res.status(404).json({error:'Order not found'});const canCustomer=existing.customer_phone===req.user.phone;const canRider=existing.rider_phone===req.user.phone&&req.user.role==='rider';let canVendor=false;if(req.user.role==='vendor'){const vp=await getRoleProfile(req.user.phone,'vendor');canVendor=!!vp&&vp.status==='approved'&&existing.vendor===vp.business_name;}const canAdmin=['admin','superadmin'].includes(req.user.role);if(!canCustomer&&!canRider&&!canVendor&&!canAdmin)return res.status(403).json({error:'Not allowed to update this order'});const r=await q('update orders set status=$1,updated_at=now(),rider_phone=case when $2 is not null then $2 else rider_phone end where id=$3 returning *',[s,canRider?req.user.phone:null,req.params.id]);await audit(req.user.phone,'order.status','order',req.params.id,{status:s});return res.json(r[0])}const o=memory.orders.get(req.params.id);if(!o)return res.status(404).json({error:'Order not found'});let memoryAllowed=false;if(o.customer_phone===req.user.phone||['admin','superadmin'].includes(req.user.role))memoryAllowed=true;if(req.user.role==='rider'&&o.rider_phone===req.user.phone)memoryAllowed=true;if(req.user.role==='vendor'){const vp=await getRoleProfile(req.user.phone,'vendor');memoryAllowed=!!vp&&vp.status==='approved'&&o.vendor===vp.business_name;}if(!memoryAllowed)return res.status(403).json({error:'Not allowed'});o.status=s;o.updated_at=new Date().toISOString();if(req.user.role==='rider')o.rider_phone=req.user.phone;res.json(o)});
app.post('/api/bookings',auth,async(req,res)=>{const id=makeId('OBU-HL-'),b={id,customer_phone:req.user.phone,hotel:req.body.hotel||'Obuasi Royal Hotel',room:req.body.room||'Executive Room',total:Number(req.body.total||450),status:'BOOKED',created_at:new Date().toISOString()};if(pool)await q('insert into bookings(id,customer_phone,hotel,room,total,status) values($1,$2,$3,$4,$5,$6)',[id,b.customer_phone,b.hotel,b.room,b.total,b.status]);else memory.bookings.set(id,b);await audit(req.user.phone,'booking.created','booking',id);res.status(201).json(b)});
app.get('/api/bookings',auth,async(req,res)=>{if(pool)return res.json(await q('select * from bookings where customer_phone=$1 order by created_at desc',[req.user.phone]));res.json([...memory.bookings.values()].filter(x=>x.customer_phone===req.user.phone))});
app.patch('/api/bookings/:id/status',auth,async(req,res)=>{const s=String(req.body.status||'').slice(0,40);if(!['BOOKED','CHECKED IN','CHECKED OUT','CANCELLED'].includes(s))return res.status(400).json({error:'Invalid booking status'});if(pool){const existing=(await q('select * from bookings where id=$1',[req.params.id]))[0];if(!existing)return res.status(404).json({error:'Booking not found'});let canHotel=false;if(req.user.role==='hotel'){const hp=await getRoleProfile(req.user.phone,'hotel');canHotel=!!hp&&hp.status==='approved'&&hp.business_name===existing.hotel;}if(existing.customer_phone!==req.user.phone&&!canHotel&&!['admin','superadmin'].includes(req.user.role))return res.status(403).json({error:'Not allowed'});const r=await q('update bookings set status=$1,updated_at=now() where id=$2 returning *',[s,req.params.id]);await audit(req.user.phone,'booking.status','booking',req.params.id,{status:s});return res.json(r[0])}const b=memory.bookings.get(req.params.id);if(!b)return res.status(404).json({error:'Booking not found'});let allowed=false;if(b.customer_phone===req.user.phone||['admin','superadmin'].includes(req.user.role))allowed=true;if(req.user.role==='hotel'){const hp=await getRoleProfile(req.user.phone,'hotel');allowed=!!hp&&hp.status==='approved'&&hp.business_name===b.hotel;}if(!allowed)return res.status(403).json({error:'Not allowed'});b.status=s;res.json(b)});
app.get('/api/bookings/:id/qr',auth,async(req,res)=>{const booking=pool?(await q('select id,customer_phone,hotel,room,status,created_at from bookings where id=$1',[req.params.id]))[0]:memory.bookings.get(req.params.id);if(!booking)return res.status(404).json({error:'Booking not found'});if(booking.customer_phone!==req.user.phone&&!['hotel','admin','superadmin'].includes(req.user.role))return res.status(403).json({error:'Not allowed'});const token=jwt.sign({bookingId:booking.id,hotel:booking.hotel,customer:booking.customer_phone,nonce:crypto.randomBytes(8).toString('hex')},SIGNING_SECRET,{expiresIn:'30m'});const qrData=await QRCode.toDataURL(token,{width:440,margin:2});res.json({bookingId:booking.id,qrToken:token,qrData,expiresIn:1800})});
app.post('/api/hotel/checkin/scan',auth,roles('hotel','admin','superadmin'),async(req,res)=>{try{const c=jwt.verify(String(req.body.qrToken||''),SIGNING_SECRET);const b=pool?(await q('select * from bookings where id=$1',[c.bookingId]))[0]:memory.bookings.get(c.bookingId);if(!b)return res.status(404).json({error:'Booking not found'});if(req.user.role==='hotel'){const hp=await getRoleProfile(req.user.phone,'hotel');if(!hp||hp.status!=='approved'||hp.business_name!==b.hotel)return res.status(403).json({error:'Booking belongs to another hotel'});}if(b.status!=='BOOKED')return res.status(400).json({error:'Booking is not available for check-in'});if(pool){const r=await q("update bookings set status='CHECKED IN',updated_at=now() where id=$1 returning *",[b.id]);await audit(req.user.phone,'hotel.checkin','booking',b.id);return res.json({ok:true,booking:r[0]})}b.status='CHECKED IN';res.json({ok:true,booking:b})}catch{return res.status(400).json({error:'Invalid or expired QR code'})}});
async function flw(pathname,body){const r=await fetch('https://api.flutterwave.com/v3'+pathname,{method:'POST',headers:{Authorization:'Bearer '+process.env.FLW_SECRET_KEY,'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.message||'Flutterwave error');return d}
app.post('/api/payments/checkout',auth,async(req,res)=>{if(!process.env.FLW_SECRET_KEY)return res.status(503).json({error:'Flutterwave is not configured'});const amount=Number(req.body.amount);if(!(amount>0))return res.status(400).json({error:'Invalid amount'});const tx_ref='OBG-'+Date.now()+'-'+crypto.randomBytes(3).toString('hex');const base=process.env.APP_URL||`${req.protocol}://${req.get('host')}`;try{const d=await flw('/payments',{tx_ref,amount,currency:'GHS',redirect_url:`${base}/payment-return`,customer:{email:req.body.email||`${req.user.phone.replace('+','')}@obuasigo.app`,name:req.body.name||'ObuasiGo Customer',phonenumber:req.user.phone},payment_options:'card,ghanamobilemoney',customizations:{title:'ObuasiGo',description:req.body.description||'ObuasiGo order payment'},meta:{entity_type:req.body.entityType||'order',entity_id:req.body.entityId||''}});if(pool)await q('insert into payments(tx_ref,user_phone,entity_type,entity_id,amount,currency,status) values($1,$2,$3,$4,$5,$6,$7)',[tx_ref,req.user.phone,req.body.entityType||'order',req.body.entityId||'',amount,'GHS','pending']);else memory.payments.set(tx_ref,{tx_ref,user_phone:req.user.phone,amount,status:'pending'});res.json({ok:true,tx_ref,link:d.data?.link})}catch(e){res.status(502).json({error:e.message})}});
app.get('/api/payments/verify/:transactionId',auth,async(req,res)=>{
 if(!process.env.FLW_SECRET_KEY)return res.status(503).json({error:'Flutterwave is not configured'});
 try{
  const r=await fetch(`https://api.flutterwave.com/v3/transactions/${encodeURIComponent(req.params.transactionId)}/verify`,{headers:{Authorization:'Bearer '+process.env.FLW_SECRET_KEY}});
  const d=await r.json(); if(!r.ok)return res.status(502).json({error:d.message||'Payment provider verification failed'});
  const tx=d.data||{}; const ref=String(tx.tx_ref||'');
  let payment=null;
  if(pool) payment=(await q('select * from payments where tx_ref=$1 and user_phone=$2',[ref,req.user.phone]))[0]||null;
  else payment=[...memory.payments.values()].find(x=>x.tx_ref===ref&&x.user_phone===req.user.phone)||null;
  if(!payment)return res.status(403).json({error:'Payment does not belong to this account'});
  const paid=String(tx.status||'').toLowerCase()==='successful';
  if(payment.amount!=null && Number(tx.amount)!==Number(payment.amount))return res.status(400).json({error:'Payment amount mismatch'});
  if(payment.currency && String(tx.currency||'').toUpperCase()!==String(payment.currency).toUpperCase())return res.status(400).json({error:'Payment currency mismatch'});
  const newStatus=paid?'successful':String(tx.status||'pending');
  if(pool)await q('update payments set status=$1,transaction_id=$2 where tx_ref=$3 and user_phone=$4',[newStatus,String(tx.id||req.params.transactionId),ref,req.user.phone]);
  else payment.status=newStatus;
  if(paid && payment.entity_type==='order' && payment.entity_id){
    if(pool){await q("update orders set status='Payment confirmed',updated_at=now() where id=$1 and customer_phone=$2",[payment.entity_id,req.user.phone]);await qualifyReferralForUser(req.user.phone)}
    else {const o=memory.orders.get(payment.entity_id);if(o&&o.customer_phone===req.user.phone){o.status='Payment confirmed';await qualifyReferralForUser(req.user.phone)}}
  }
  res.json({ok:true,status:newStatus,transactionId:tx.id,tx_ref:ref,amount:tx.amount,currency:tx.currency,entityType:payment.entity_type,entityId:payment.entity_id});
 }catch(e){res.status(502).json({error:e.message})}
});
app.post('/api/webhooks/flutterwave',async(req,res)=>{const hash=req.headers['verif-hash'];if(!process.env.FLW_SECRET_HASH||hash!==process.env.FLW_SECRET_HASH)return res.status(401).end();const body=req.body||{};const tx=body.data||body;const ref=tx.tx_ref;if(ref){if(pool){await q('update payments set status=$1,transaction_id=$2 where tx_ref=$3',[tx.status||'completed',String(tx.id||''),ref]);const pay=(await q('select entity_type,entity_id,status from payments where tx_ref=$1',[ref]))[0];if(pay?.entity_type==='order'&&pay.entity_id&&String(tx.status||'').toLowerCase()==='successful'){await q("update orders set status='Payment confirmed',updated_at=now() where id=$1",[pay.entity_id]);const order=(await q('select customer_phone from orders where id=$1',[pay.entity_id]))[0];if(order?.customer_phone)await qualifyReferralForUser(order.customer_phone)}}else if(memory.payments.has(ref)){const pay=memory.payments.get(ref);pay.status=tx.status||'completed';if(pay.entity_type==='order'&&pay.entity_id&&String(tx.status||'').toLowerCase()==='successful'){const o=memory.orders.get(pay.entity_id);if(o){o.status='Payment confirmed';await qualifyReferralForUser(o.customer_phone)}}}}res.json({ok:true})});
app.get('/api/rider/dashboard',auth,roles('rider'),async(req,res)=>{let orders=pool?await q('select * from orders where rider_phone=$1 order by updated_at desc limit 50',[req.user.phone]):[...memory.orders.values()].filter(x=>x.rider_phone===req.user.phone);let feedback=pool?await q('select * from order_feedback where rider_phone=$1 order by created_at desc limit 20',[req.user.phone]):[...memory.feedback.values()].filter(x=>x.rider_phone===req.user.phone);const earnings=orders.filter(x=>['Delivered','COMPLETED','Delivered to customer'].includes(x.status)).map(x=>Number(x.total||0)*0.15);res.json({orders,feedback,earnings,summary:{today:earnings.slice(-7).reduce((a,b)=>a+b,0),deliveries:orders.length,averageRating:feedback.length?feedback.reduce((a,b)=>a+b.rating,0)/feedback.length:0}})});
app.get('/api/search',async(req,res)=>{try{const data=await searchCatalog(req.query.q||'',req.query.type||'all');res.json({ok:true,results:data})}catch(e){res.status(500).json({error:'Search failed'})}});

app.post('/api/partner/apply',auth,async(req,res)=>{
  const requestedRole=cleanText(req.body.requested_role,20).toLowerCase();
  if(!['rider','vendor','hotel'].includes(requestedRole))return res.status(400).json({error:'Choose rider, vendor or hotel'});
  const common={full_name:cleanText(req.body.full_name,120),ghana_card_number:cleanText(req.body.ghana_card_number,80),address:cleanText(req.body.address,240),email:cleanText(req.body.email,160)};
  try{
    if(pool){
      if(requestedRole==='rider'){
        await q(`insert into rider_profiles(phone,full_name,ghana_card_name,ghana_card_number,license_number,vehicle_type,plate_number,address,emergency_phone,metadata) values($1,$2,$2,$3,$4,$5,$6,$7,$8,$9) on conflict(phone) do update set full_name=$2,ghana_card_name=$2,ghana_card_number=$3,license_number=$4,vehicle_type=$5,plate_number=$6,address=$7,emergency_phone=$8,metadata=$9,updated_at=now()`,[req.user.phone,common.full_name,common.ghana_card_number,cleanText(req.body.license_number,80),cleanText(req.body.vehicle_type,40),cleanText(req.body.plate_number,40),common.address,cleanText(req.body.emergency_phone,40),JSON.stringify({email:common.email})]);
      }else{
        const existing=(await q('select id from business_profiles where owner_phone=$1 and kind=$2 limit 1',[req.user.phone,requestedRole]))[0];
        let b;if(existing)b=(await q(`update business_profiles set business_name=$1,business_phone=$2,email=$3,address=$4,description=$5,ghana_card_name=$6,ghana_card_number=$7,registration_number=$8,metadata=$9,status='pending',updated_at=now() where id=$10 returning *`,[cleanText(req.body.business_name,160),cleanText(req.body.business_phone,40),common.email,common.address,cleanText(req.body.description,500),common.full_name,common.ghana_card_number,cleanText(req.body.registration_number,100),JSON.stringify({businessType:cleanText(req.body.business_type,80),hours:cleanText(req.body.hours,120)}),existing.id]))[0];else b=(await q(`insert into business_profiles(owner_phone,kind,business_name,business_phone,email,address,description,ghana_card_name,ghana_card_number,registration_number,metadata) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) returning *`,[req.user.phone,requestedRole,cleanText(req.body.business_name,160),cleanText(req.body.business_phone,40),common.email,common.address,cleanText(req.body.description,500),common.full_name,common.ghana_card_number,cleanText(req.body.registration_number,100),JSON.stringify({businessType:cleanText(req.body.business_type,80),hours:cleanText(req.body.hours,120)})]))[0];
        if(Array.isArray(req.body.catalog)){for(const item of req.body.catalog.slice(0,50)){if(!item?.name)continue;await q('insert into catalog_items(business_id,name,category,price,description) values($1,$2,$3,$4,$5)',[b.id,cleanText(item.name,120),cleanText(item.category,60),Math.max(0,Number(item.price||0)),cleanText(item.description,240)])}}
      }
      const a=(await q(`insert into role_applications(phone,requested_role,business_name,notes,status) values($1,$2,$3,$4,'pending') returning *`,[req.user.phone,requestedRole,cleanText(req.body.business_name,160),cleanText(req.body.notes,500)]))[0];
      await audit(req.user.phone,'role.application','role_application',a.id,{requestedRole});return res.status(201).json({ok:true,application:a,message:'Application submitted for admin review'});
    }
    const id=crypto.randomUUID();const item={id,phone:req.user.phone,requested_role:requestedRole,business_name:cleanText(req.body.business_name,160),status:'pending',created_at:new Date().toISOString()};memory.applications.set(id,item);
    if(requestedRole==='rider')memory.riders.set(req.user.phone,{phone:req.user.phone,...common,license_number:cleanText(req.body.license_number,80),vehicle_type:cleanText(req.body.vehicle_type,40),plate_number:cleanText(req.body.plate_number,40),status:'pending'});
    else memory.businesses.set(id,{id,owner_phone:req.user.phone,kind:requestedRole,business_name:item.business_name,business_phone:cleanText(req.body.business_phone,40),email:common.email,address:common.address,description:cleanText(req.body.description,500),status:'pending'});
    await audit(req.user.phone,'role.application','role_application',id,{requestedRole});res.status(201).json({ok:true,application:item,message:'Application submitted for admin review'});
  }catch(e){console.error('partner apply',e);res.status(500).json({error:'Could not submit application'})}
});

app.post('/api/admin/access-request',auth,async(req,res)=>{const fullName=cleanText(req.body.full_name,120),ghana=cleanText(req.body.ghana_card_number,80),reason=cleanText(req.body.reason,500);if(!fullName||!ghana||!reason)return res.status(400).json({error:'Full name, Ghana Card number and reason are required'});if(pool){const r=(await q(`insert into admin_access_requests(phone,full_name,ghana_card_number,reason) values($1,$2,$3,$4) returning id,phone,full_name,status,created_at`,[req.user.phone,fullName,ghana,reason]))[0];await audit(req.user.phone,'admin.access_request','admin_access_request',r.id);return res.status(201).json(r)}const id=crypto.randomUUID(),r={id,phone:req.user.phone,full_name:fullName,ghana_card_number:ghana,reason,status:'pending',created_at:new Date().toISOString()};memory.adminRequests.set(id,r);res.status(201).json(r)});

app.get('/api/admin/applications',auth,admin,async(req,res)=>{if(pool)return res.json(await q(`select * from role_applications order by created_at desc limit 200`));res.json([...memory.applications.values()].sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))))});
app.get('/api/admin/access-requests',auth,admin,async(req,res)=>{if(pool)return res.json(await q(`select id,phone,full_name,ghana_card_number,reason,status,created_at,reviewed_at from admin_access_requests order by created_at desc limit 100`));res.json([...memory.adminRequests.values()])});
app.patch('/api/admin/access-requests/:id',auth,admin,async(req,res)=>{const status=cleanText(req.body.status,20);if(!['approved','rejected'].includes(status))return res.status(400).json({error:'Invalid status'});if(pool){const a=(await q('select * from admin_access_requests where id=$1',[req.params.id]))[0];if(!a)return res.status(404).json({error:'Request not found'});await q('update admin_access_requests set status=$1,reviewed_at=now() where id=$2',[status,req.params.id]);if(status==='approved')await q("update users set role='admin',updated_at=now() where phone=$1",[a.phone]);await audit(req.user.phone,'admin.access_request.review','admin_access_request',a.id,{status});return res.json({ok:true,status})}const a=memory.adminRequests.get(req.params.id);if(!a)return res.status(404).json({error:'Request not found'});a.status=status;a.reviewed_at=new Date().toISOString();if(status==='approved'){const u=memory.users.get(a.phone);if(u)u.role='admin'}res.json({ok:true,status})});
app.patch('/api/admin/applications/:id',auth,admin,async(req,res)=>{const status=cleanText(req.body.status,20);if(!['approved','rejected'].includes(status))return res.status(400).json({error:'Invalid application status'});if(pool){const a=(await q('select * from role_applications where id=$1',[req.params.id]))[0];if(!a)return res.status(404).json({error:'Application not found'});await q('update role_applications set status=$1,reviewed_at=now() where id=$2',[status,req.params.id]);if(status==='approved'){await q('update users set role=$1,updated_at=now() where phone=$2',[a.requested_role,a.phone]);if(a.requested_role==='vendor'||a.requested_role==='hotel')await q('update business_profiles set status=\'approved\',updated_at=now() where owner_phone=$1 and kind=$2',[a.phone,a.requested_role]);else await q('update rider_profiles set status=\'approved\',updated_at=now() where phone=$1',[a.phone]);}else{if(a.requested_role==='vendor'||a.requested_role==='hotel')await q('update business_profiles set status=\'rejected\',updated_at=now() where owner_phone=$1 and kind=$2',[a.phone,a.requested_role]);else await q('update rider_profiles set status=\'rejected\',updated_at=now() where phone=$1',[a.phone]);}await audit(req.user.phone,'role.application.review','role_application',a.id,{status});return res.json({ok:true,status})}const a=memory.applications.get(req.params.id);if(!a)return res.status(404).json({error:'Application not found'});a.status=status;if(status==='approved'){const u=memory.users.get(a.phone);if(u)u.role=a.requested_role;if(a.requested_role==='vendor'||a.requested_role==='hotel'){const b=[...memory.businesses.values()].find(x=>x.owner_phone===a.phone&&x.kind===a.requested_role);if(b)b.status='approved'}else{const r=memory.riders.get(a.phone);if(r)r.status='approved'}}res.json({ok:true,status})});
app.patch('/api/admin/access-requests/:id',auth,admin,async(req,res)=>{const status=cleanText(req.body.status,20);if(!['approved','rejected'].includes(status))return res.status(400).json({error:'Invalid status'});if(pool){const r=(await q('update admin_access_requests set status=$1,reviewed_at=now() where id=$2 returning *',[status,req.params.id]))[0];if(!r)return res.status(404).json({error:'Request not found'});if(status==='approved')await q('update users set role=\'admin\',updated_at=now() where phone=$1',[r.phone]);await audit(req.user.phone,'admin.access_request.review','admin_access_request',req.params.id,{status});return res.json(r)}const r=memory.adminRequests.get(req.params.id);if(!r)return res.status(404).json({error:'Request not found'});r.status=status;if(status==='approved'){const u=memory.users.get(r.phone);if(u)u.role='admin'}res.json(r)});

app.post('/api/vendor/catalog',auth,roles('vendor'),async(req,res)=>{const p=await getRoleProfile(req.user.phone,'vendor');if(!p||p.status!=='approved')return res.status(403).json({error:'Vendor business is not approved'});const name=cleanText(req.body.name,120),category=cleanText(req.body.category,60),price=Number(req.body.price);if(!name||!(price>=0))return res.status(400).json({error:'Item name and valid price are required'});if(pool){const r=(await q('insert into catalog_items(business_id,name,category,price,description) values($1,$2,$3,$4,$5) returning *',[p.id,name,category,price,cleanText(req.body.description,240)]))[0];return res.status(201).json(r)}const id=crypto.randomUUID(),x={id,business_id:p.id,name,category,price,description:cleanText(req.body.description,240),active:true};memory.catalog.set(id,x);res.status(201).json(x)});
app.get('/api/vendor/profile',auth,roles('vendor'),async(req,res)=>{const p=await getRoleProfile(req.user.phone,'vendor');if(!p)return res.status(404).json({error:'Vendor profile not found'});if(pool){p.items=await q('select * from catalog_items where business_id=$1 order by created_at desc',[p.id])}else p.items=[...memory.catalog.values()].filter(x=>x.business_id===p.id);res.json(p)});
app.get('/api/hotel/profile',auth,roles('hotel'),async(req,res)=>{const p=await getRoleProfile(req.user.phone,'hotel');if(!p)return res.status(404).json({error:'Hotel profile not found'});if(pool)p.rooms=await q('select * from catalog_items where business_id=$1 order by created_at desc',[p.id]);else p.rooms=[...memory.catalog.values()].filter(x=>x.business_id===p.id);res.json(p)});
app.post('/api/hotel/catalog',auth,roles('hotel'),async(req,res)=>{const p=await getRoleProfile(req.user.phone,'hotel');if(!p||p.status!=='approved')return res.status(403).json({error:'Hotel is not approved'});const name=cleanText(req.body.name,120),price=Number(req.body.price);if(!name||!(price>=0))return res.status(400).json({error:'Room name and valid price are required'});if(pool){const r=(await q('insert into catalog_items(business_id,name,category,price,description) values($1,$2,$3,$4,$5) returning *',[p.id,name,'room',price,cleanText(req.body.description,240)]))[0];return res.status(201).json(r)}const id=crypto.randomUUID(),x={id,business_id:p.id,name,category:'room',price,description:cleanText(req.body.description,240),active:true};memory.catalog.set(id,x);res.status(201).json(x)});

app.get('/api/vendor/orders',auth,roles('vendor','admin','superadmin'),async(req,res)=>{let vendor=String(req.query.vendor||'');if(req.user.role==='vendor'){const p=await getRoleProfile(req.user.phone,'vendor');if(!p||p.status!=='approved')return res.status(403).json({error:'Vendor business is not approved'});vendor=p.business_name}else if(!vendor)vendor='';if(pool)return res.json(vendor?await q('select id,vendor,items,total,status,created_at,rider_phone,delivery_address from orders where vendor=$1 order by created_at desc limit 100',[vendor]):await q('select id,vendor,items,total,status,created_at,rider_phone,delivery_address from orders order by created_at desc limit 100'));res.json([...memory.orders.values()].filter(x=>!vendor||x.vendor===vendor).map(({customer_phone,...x})=>x)) });
app.get('/api/hotel/bookings',auth,roles('hotel','admin','superadmin'),async(req,res)=>{let hotel=String(req.query.hotel||'');if(req.user.role==='hotel'){const p=await getRoleProfile(req.user.phone,'hotel');if(!p||p.status!=='approved')return res.status(403).json({error:'Hotel is not approved'});hotel=p.business_name}else if(!hotel)hotel='';if(pool)return res.json(hotel?await q('select id,hotel,room,total,status,created_at from bookings where hotel=$1 order by created_at desc limit 100',[hotel]):await q('select id,hotel,room,total,status,created_at from bookings order by created_at desc limit 100'));res.json([...memory.bookings.values()].filter(x=>!hotel||x.hotel===hotel).map(({customer_phone,...x})=>x)) });
app.patch('/api/orders/:id/location',auth,roles('customer'),async(req,res)=>{const lat=Number(req.body.lat),lng=Number(req.body.lng);if(!Number.isFinite(lat)||!Number.isFinite(lng))return res.status(400).json({error:'Invalid location'});if(pool){const r=await q('update orders set delivery_lat=$1,delivery_lng=$2,delivery_address=$3,updated_at=now() where id=$4 and customer_phone=$5 returning *',[lat,lng,String(req.body.address||'').slice(0,240),req.params.id,req.user.phone]);if(!r[0])return res.status(404).json({error:'Order not found'});return res.json(r[0])}const o=memory.orders.get(req.params.id);if(!o||o.customer_phone!==req.user.phone)return res.status(404).json({error:'Order not found'});o.delivery_lat=lat;o.delivery_lng=lng;o.delivery_address=String(req.body.address||'').slice(0,240);res.json(o)});
app.post('/api/orders/:id/feedback',auth,roles('customer'),async(req,res)=>{const rating=Number(req.body.rating),comment=String(req.body.comment||'').slice(0,500);if(!Number.isInteger(rating)||rating<1||rating>5)return res.status(400).json({error:'Rating must be 1 to 5'});if(pool){const o=(await q('select id,rider_phone,status from orders where id=$1 and customer_phone=$2',[req.params.id,req.user.phone]))[0];if(!o)return res.status(404).json({error:'Order not found'});if(!o.rider_phone)return res.status(400).json({error:'No rider is assigned yet'});const r=await q('insert into order_feedback(order_id,customer_phone,rider_phone,rating,comment) values($1,$2,$3,$4,$5) on conflict(order_id) do update set rating=$4,comment=$5 returning *',[o.id,req.user.phone,o.rider_phone,rating,comment]);await audit(req.user.phone,'order.feedback','order',o.id,{rating});return res.status(201).json(r[0])}const o=memory.orders.get(req.params.id);if(!o||o.customer_phone!==req.user.phone)return res.status(404).json({error:'Order not found'});if(!o.rider_phone)return res.status(400).json({error:'No rider is assigned yet'});const f={id:crypto.randomUUID(),order_id:o.id,customer_phone:req.user.phone,rider_phone:o.rider_phone,rating,comment,created_at:new Date().toISOString()};memory.feedback.set(o.id,f);res.status(201).json(f)});
app.get('/api/rider/feedback',auth,roles('rider'),async(req,res)=>res.json(pool?await q('select order_id,rating,comment,created_at from order_feedback where rider_phone=$1 order by created_at desc',[req.user.phone]):[...memory.feedback.values()].filter(x=>x.rider_phone===req.user.phone).map(({order_id,rating,comment,created_at})=>({order_id,rating,comment,created_at}))));
app.post('/api/tracking/:orderId',auth,async(req,res)=>{if(req.user.role!=='rider')return res.status(403).json({error:'Rider access required'});const lat=Number(req.body.lat),lng=Number(req.body.lng),accuracy=Number(req.body.accuracy||0);if(!Number.isFinite(lat)||!Number.isFinite(lng))return res.status(400).json({error:'Invalid coordinates'});const p={orderId:req.params.orderId,lat,lng,accuracy,at:new Date().toISOString()};if(pool)await q('insert into tracking_points(order_id,lat,lng,accuracy) values($1,$2,$3,$4)',[p.orderId,lat,lng,accuracy]);else memory.tracking.set(p.orderId,p);broadcast(p.orderId,{type:'location',...p});res.json({ok:true,p})});
const sockets=new Map();let WebSocket;try{WebSocket=require('ws')}catch{}function broadcast(orderId,msg){for(const ws of sockets.get(orderId)||[])if(ws.readyState===1)ws.send(JSON.stringify(msg))}
const httpServer=require('http').createServer(app);if(WebSocket){const wss=new WebSocket.Server({server:httpServer,path:'/ws'});wss.on('connection',(ws,req)=>{const u=new URL(req.url,'http://localhost');const orderId=u.searchParams.get('orderId'),token=u.searchParams.get('token');let claims;try{claims=jwt.verify(token||'',SIGNING_SECRET)}catch{return ws.close(1008,'Unauthorized')}if(!orderId)return ws.close(1008,'Order required');if(!sockets.has(orderId))sockets.set(orderId,new Set());sockets.get(orderId).add(ws);ws.on('close',()=>sockets.get(orderId)?.delete(ws));ws.send(JSON.stringify({type:'connected',orderId}))})}
const vapidReady=!!(process.env.VAPID_PUBLIC_KEY&&process.env.VAPID_PRIVATE_KEY&&process.env.VAPID_SUBJECT);if(vapidReady)webpush.setVapidDetails(process.env.VAPID_SUBJECT,process.env.VAPID_PUBLIC_KEY,process.env.VAPID_PRIVATE_KEY);
app.get('/api/push/public-key',(req,res)=>res.json({configured:vapidReady,publicKey:vapidReady?process.env.VAPID_PUBLIC_KEY:null}));app.post('/api/push/subscribe',auth,async(req,res)=>{if(!vapidReady)return res.status(503).json({error:'Push not configured'});const sub=req.body.subscription;if(!sub?.endpoint)return res.status(400).json({error:'Invalid subscription'});if(pool)await q('insert into push_subscriptions(user_phone,endpoint,subscription) values($1,$2,$3) on conflict(endpoint) do update set subscription=$3,user_phone=$1',[req.user.phone,sub.endpoint,JSON.stringify(sub)]);else memory.push.set(sub.endpoint,{phone:req.user.phone,subscription:sub});res.json({ok:true})});
app.post('/api/push/send',auth,admin,async(req,res)=>{if(!vapidReady)return res.status(503).json({error:'Push not configured'});let subs=pool?await q('select * from push_subscriptions where user_phone=$1',[req.body.phone]):[...memory.push.values()].filter(x=>x.phone===req.body.phone);for(const s of subs){const sub=s.subscription||s;try{await webpush.sendNotification(sub,JSON.stringify({title:req.body.title||'ObuasiGo',body:req.body.body||'You have an update'}))}catch(e){console.error('push',e.message)}}res.json({ok:true})});
app.post('/api/documents',auth,upload.single('document'),async(req,res)=>{if(!req.file)return res.status(400).json({error:'Document file required'});if(process.env.NODE_ENV==='production'&&!(process.env.SUPABASE_URL&&process.env.SUPABASE_SERVICE_ROLE_KEY&&process.env.SUPABASE_STORAGE_BUCKET))return res.status(503).json({error:'Private document storage is not configured'});const allowed=['image/jpeg','image/png','application/pdf'];if(!allowed.includes(req.file.mimetype))return res.status(400).json({error:'Only JPG, PNG or PDF allowed'});let url=null;if(process.env.SUPABASE_URL&&process.env.SUPABASE_SERVICE_ROLE_KEY&&process.env.SUPABASE_STORAGE_BUCKET){const {createClient}=require('@supabase/supabase-js');const sb=createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY);const filePath=`documents/${req.user.phone.replace(/\W/g,'_')}/${Date.now()}-${req.file.originalname.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const up=await sb.storage.from(process.env.SUPABASE_STORAGE_BUCKET).upload(filePath,req.file.buffer,{contentType:req.file.mimetype,upsert:false});if(up.error)return res.status(502).json({error:'Document storage failed'});url=up.data.path}const type=String(req.body.type||'identity').slice(0,40);if(!['identity','ghana_card','ghana_card_front','ghana_card_back','driver_license','vehicle','vehicle_registration','vehicle_insurance','selfie','business_registration','food_license','hotel_license','proof_of_address'].includes(type))return res.status(400).json({error:'Invalid document type'});if(pool){const r=await q('insert into documents(user_phone,doc_type,file_url) values($1,$2,$3) returning *',[req.user.phone,type,url]);return res.status(201).json(r[0])}const d={id:crypto.randomUUID(),user_phone:req.user.phone,doc_type:type,file_url:url,status:'pending'};memory.documents.set(d.id,d);res.status(201).json(d)});
app.get('/api/admin/orders',auth,admin,async(req,res)=>res.json(pool?await q('select id,vendor,total,status,rider_phone,created_at,delivery_lat,delivery_lng,delivery_address from orders order by created_at desc limit 100'):[...memory.orders.values()].map(({customer_phone,...x})=>x)));
app.get('/api/admin/bookings',auth,admin,async(req,res)=>res.json(pool?await q('select id,hotel,room,total,status,customer_phone,created_at from bookings order by created_at desc limit 100'):[...memory.bookings.values()].map(({customer_phone,...x})=>x)));
app.get('/api/admin/feedback',auth,admin,async(req,res)=>res.json(pool?await q('select order_id,rider_phone,rating,comment,created_at from order_feedback order by created_at desc limit 100'):[...memory.feedback.values()].map(({customer_phone,...x})=>x)));
app.get('/api/admin/overview',auth,admin,async(req,res)=>{if(pool){const [[customers],[riders],[vendors],[hotels],[orders],[bookings],[pending]] = await Promise.all([q("select count(*) n from users where role='customer'"),q("select count(*) n from users where role='rider'"),q("select count(*) n from users where role='vendor'"),q("select count(*) n from users where role='hotel'"),q('select count(*) n from orders'),q('select count(*) n from bookings'),q("select count(*) n from documents where status='pending'")]);return res.json({customers:+customers[0].n,riders:+riders[0].n,vendors:+vendors[0].n,hotels:+hotels[0].n,orders:+orders[0].n,bookings:+bookings[0].n,pendingDocuments:+pending[0].n})}res.json({customers:memory.users.size,riders:0,vendors:0,hotels:0,orders:memory.orders.size,bookings:memory.bookings.size,pendingDocuments:memory.documents.size})});
app.get('/api/admin/documents',auth,admin,async(req,res)=>res.json(pool?await q("select * from documents where status='pending' order by created_at asc"):Array.from(memory.documents.values()).filter(x=>x.status==='pending')));
app.patch('/api/admin/documents/:id',auth,admin,async(req,res)=>{if(pool){const r=await q('update documents set status=$1 where id=$2 returning *',[req.body.status,req.params.id]);if(!r[0])return res.status(404).json({error:'Document not found'});return res.json(r[0])}const d=memory.documents.get(req.params.id);if(!d)return res.status(404).json({error:'Document not found'});d.status=req.body.status;res.json(d)});

app.get('/api/partner/status',auth,async(req,res)=>{if(pool){const applications=await q('select id,requested_role,business_name,status,created_at,reviewed_at from role_applications where phone=$1 order by created_at desc',[req.user.phone]);const rider=(await q('select * from rider_profiles where phone=$1',[req.user.phone]))[0]||null;const vendors=await q("select * from business_profiles where owner_phone=$1 and kind='vendor' order by created_at desc limit 1",[req.user.phone]);const hotels=await q("select * from business_profiles where owner_phone=$1 and kind='hotel' order by created_at desc limit 1",[req.user.phone]);return res.json({applications,rider,vendor:vendors[0]||null,hotel:hotels[0]||null});}return res.json({applications:[...memory.applications.values()].filter(x=>x.phone===req.user.phone),rider:memory.riders.get(req.user.phone)||null,vendor:[...memory.businesses.values()].find(x=>x.owner_phone===req.user.phone&&x.kind==='vendor')||null,hotel:[...memory.businesses.values()].find(x=>x.owner_phone===req.user.phone&&x.kind==='hotel')||null});});
app.get('/api/admin/partners',auth,admin,async(req,res)=>{if(pool){const vendors=await q("select * from business_profiles where kind='vendor' order by created_at desc limit 200");const hotels=await q("select * from business_profiles where kind='hotel' order by created_at desc limit 200");const riders=await q('select * from rider_profiles order by created_at desc limit 200');return res.json({vendors,hotels,riders});}return res.json({vendors:[...memory.businesses.values()].filter(x=>x.kind==='vendor'),hotels:[...memory.businesses.values()].filter(x=>x.kind==='hotel'),riders:[...memory.riders.values()]});});
app.patch('/api/admin/partners/:kind/:id/status',auth,admin,async(req,res)=>{const kind=String(req.params.kind);const status=cleanText(req.body.status,20);if(!['vendor','hotel','rider'].includes(kind)||!['approved','rejected','pending'].includes(status))return res.status(400).json({error:'Invalid partner status'});if(pool){let r;if(kind==='rider')r=await q('update rider_profiles set status=$1,updated_at=now() where phone=$2 returning *',[status,req.params.id]);else r=await q('update business_profiles set status=$1,updated_at=now() where id=$2 returning *',[status,req.params.id]);if(!r[0])return res.status(404).json({error:'Partner not found'});const phone=kind==='rider'?r[0].phone:r[0].owner_phone;if(status==='approved')await q('update users set role=$1,updated_at=now() where phone=$2',[kind,phone]);if(status==='rejected'&&kind!=='rider')await q("update users set role=case when role=$1 then 'customer' else role end where phone=$2",[kind,phone]);if(status==='rejected'&&kind==='rider')await q("update users set role=case when role='rider' then 'customer' else role end where phone=$1",[phone]);await audit(req.user.phone,'partner.status','partner',String(req.params.id),{kind,status});return res.json({ok:true,partner:r[0]});}const collection=kind==='rider'?memory.riders:memory.businesses;const obj=collection.get(req.params.id);if(!obj)return res.status(404).json({error:'Partner not found'});obj.status=status;const phone=kind==='rider'?obj.phone:obj.owner_phone;if(status==='approved'){const u=memory.users.get(phone);if(u)u.role=kind;}if(status==='rejected'){const u=memory.users.get(phone);if(u&&u.role===kind)u.role='customer';}res.json({ok:true,partner:obj});});
app.get('/api/admin/profile',auth,admin,async(req,res)=>res.json({owner:OWNER_NAME,phone:req.user.phone,role:req.user.role}));

app.get('/vendor',(req,res)=>res.sendFile(path.join(__dirname,'public','vendor.html')));app.get('/hotel',(req,res)=>res.sendFile(path.join(__dirname,'public','hotel.html')));app.get('/rider',(req,res)=>res.sendFile(path.join(__dirname,'public','rider.html')));app.get('/admin',(req,res)=>res.sendFile(path.join(__dirname,'public','admin.html')));
app.get('/payment-return',(req,res)=>res.sendFile(path.join(__dirname,'public','payment-return.html')));
app.get('/privacy',(req,res)=>res.sendFile(path.join(__dirname,'public','privacy.html')));
app.get('/terms',(req,res)=>res.sendFile(path.join(__dirname,'public','terms.html')));
app.get('/refunds',(req,res)=>res.sendFile(path.join(__dirname,'public','refunds.html')));
app.get('/cookies',(req,res)=>res.sendFile(path.join(__dirname,'public','cookies.html')));
app.get('/404',(req,res)=>res.status(404).sendFile(path.join(__dirname,'public','404.html')));
app.get('/api/public-config',(req,res)=>res.json({analyticsId:process.env.ANALYTICS_ID||null,appName:'ObuasiGo'}));
app.use('/api',(req,res)=>res.status(404).json({error:'API route not found'}));
app.use((req,res)=>res.status(404).sendFile(path.join(__dirname,'public','404.html')));
initDb().then(()=>httpServer.listen(PORT,()=>console.log(`ObuasiGo running on ${PORT}`))).catch(e=>{console.error('DB init failed',e);process.exit(1)});
