const express=require('express');const cors=require('cors');const jwt=require('jsonwebtoken');const path=require('path');const crypto=require('crypto');const twilio=require('twilio');const {Pool}=require('pg');const multer=require('multer');const helmet=require('helmet');const rateLimit=require('express-rate-limit');const webpush=require('web-push');require('dotenv').config();
const app=express();const PORT=process.env.PORT||3000;const JWT_SECRET=process.env.JWT_SECRET;
if(!JWT_SECRET && process.env.NODE_ENV==='production'){throw new Error('JWT_SECRET is required in production');}
const SIGNING_SECRET=JWT_SECRET||crypto.randomBytes(32).toString('hex');
app.set('trust proxy',1);
const allowedOrigins=(process.env.ALLOWED_ORIGINS||'').split(',').map(x=>x.trim()).filter(Boolean);
app.use(helmet({contentSecurityPolicy:false,referrerPolicy:{policy:'no-referrer'},crossOriginEmbedderPolicy:false}));
app.use(cors({origin:(origin,cb)=>{if(!origin||allowedOrigins.length===0||allowedOrigins.includes(origin))return cb(null,true);cb(new Error('Origin not allowed'));},methods:['GET','POST','PATCH','PUT','DELETE','OPTIONS'],allowedHeaders:['Content-Type','Authorization'],credentials:false}));
app.use(express.json({limit:'1mb'}));app.use(express.urlencoded({extended:false,limit:'1mb'}));
const apiLimiter=rateLimit({windowMs:60*1000,max:120,standardHeaders:true,legacyHeaders:false,message:{error:'Too many requests'}});
app.use('/api/',apiLimiter);
app.use(express.static(path.join(__dirname,'public'),{dotfiles:'deny',index:false}));
const authLimiter=rateLimit({windowMs:15*60*1000,max:20,standardHeaders:true,legacyHeaders:false});
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:6*1024*1024}});
const pool=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_SSL==='false'?false:{rejectUnauthorized:false}}):null;
const memory={users:new Map(),orders:new Map(),bookings:new Map(),payments:new Map(),documents:new Map(),tracking:new Map(),push:new Map(),audit:[]};
async function q(text,params=[]){if(!pool)throw new Error('DATABASE_NOT_CONFIGURED');return (await pool.query(text,params)).rows}
async function initDb(){if(!pool)return;await pool.query(`create table if not exists users(id uuid primary key default gen_random_uuid(),phone text unique not null,email text,full_name text,role text default 'customer',verified boolean default false,status text default 'active',created_at timestamptz default now());create table if not exists orders(id text primary key,customer_phone text not null,vendor text,items jsonb default '[]',total numeric default 0,status text,created_at timestamptz default now(),updated_at timestamptz default now(),rider_phone text,pickup_code text default '4821',delivery_pin text default '7392');create table if not exists bookings(id text primary key,customer_phone text not null,hotel text,room text,total numeric default 0,status text,created_at timestamptz default now(),updated_at timestamptz default now());create table if not exists payments(tx_ref text primary key,user_phone text,entity_type text,entity_id text,amount numeric,currency text default 'GHS',status text default 'pending',provider text default 'flutterwave',transaction_id text,created_at timestamptz default now());create table if not exists tracking_points(id bigserial primary key,order_id text,lat double precision,lng double precision,accuracy double precision,created_at timestamptz default now());create table if not exists documents(id uuid primary key default gen_random_uuid(),user_phone text,doc_type text,file_url text,status text default 'pending',created_at timestamptz default now());create table if not exists push_subscriptions(id uuid primary key default gen_random_uuid(),user_phone text,endpoint text unique,subscription jsonb,created_at timestamptz default now());create table if not exists audit_logs(id bigserial primary key,actor text,action text,entity_type text,entity_id text,meta jsonb,created_at timestamptz default now());`)}
function normalizePhone(p){return String(p||'').replace(/[\s()-]/g,'')}function validE164(p){return /^\+[1-9]\d{7,14}$/.test(p)}
const twilioConfigured=!!(process.env.TWILIO_ACCOUNT_SID&&process.env.TWILIO_AUTH_TOKEN&&process.env.TWILIO_VERIFY_SERVICE_SID);const twilioClient=twilioConfigured?twilio(process.env.TWILIO_ACCOUNT_SID,process.env.TWILIO_AUTH_TOKEN):null;
async function sendOtp(phone){if(twilioConfigured){const v=await twilioClient.verify.v2.services(process.env.TWILIO_VERIFY_SERVICE_SID).verifications.create({to:phone,channel:'sms'});return{provider:'twilio',status:v.status}}if(process.env.DEV_OTP==='true'){global.devOtps=global.devOtps||new Map();const code=String(Math.floor(100000+Math.random()*900000));global.devOtps.set(phone,{code,expires:Date.now()+300000});console.log('[DEV OTP]',phone,code);return{provider:'development',status:'pending',devOtp:code}}throw Object.assign(new Error('OTP service not configured'),{statusCode:503})}
async function verifyOtp(phone,code){if(twilioConfigured)return twilioClient.verify.v2.services(process.env.TWILIO_VERIFY_SERVICE_SID).verificationChecks.create({to:phone,code});const r=global.devOtps?.get(phone);if(!r||Date.now()>r.expires)return{status:'canceled'};global.devOtps.delete(phone);return{status:r.code===code?'approved':'pending'}}
async function getUser(phone){if(pool){const r=await q('select * from users where phone=$1',[phone]);return r[0]}return memory.users.get(phone)}
function configuredRole(phone){const admins=(process.env.ADMIN_PHONES||'').split(',').map(normalizePhone).filter(Boolean);return admins.includes(phone)?'admin':'customer'}
async function upsertUser(phone){const role=configuredRole(phone);if(pool){const r=await q(`insert into users(phone,role,verified) values($1,$2,true) on conflict(phone) do update set verified=true,role=case when $2='admin' then 'admin' else users.role end returning *`,[phone,role]);return r[0]}let u=memory.users.get(phone)||{phone,role,verified:true,createdAt:new Date().toISOString()};u.verified=true;if(role==='admin')u.role='admin';memory.users.set(phone,u);return u}
function auth(req,res,next){try{req.user=jwt.verify((req.headers.authorization||'').replace(/^Bearer\s+/,'').trim(),SIGNING_SECRET);next()}catch{return res.status(401).json({error:'Authentication required'})}}
function admin(req,res,next){if(!['admin','superadmin'].includes(req.user.role))return res.status(403).json({error:'Admin access required'});next()}
function roles(...allowed){return (req,res,next)=>allowed.includes(req.user.role)?next():res.status(403).json({error:'Insufficient permissions'})}
async function audit(actor,action,type,id,meta={}){if(pool)await q('insert into audit_logs(actor,action,entity_type,entity_id,meta) values($1,$2,$3,$4,$5)',[actor,action,type,id,JSON.stringify(meta)]);else memory.audit.push({actor,action,type,id,meta,at:new Date().toISOString()})}
app.get('/api/health',async(req,res)=>res.json({ok:true,service:'ObuasiGo API',database:pool?'postgres':'memory-dev',otpProvider:twilioConfigured?'twilio-verify':process.env.DEV_OTP==='true'?'development':'not-configured',payments:process.env.FLW_SECRET_KEY?'flutterwave':'not-configured',maps:'browser-geolocation+leaflet',push:process.env.VAPID_PUBLIC_KEY?'web-push':'not-configured',time:new Date().toISOString()}));
app.post('/api/auth/request-otp',authLimiter,async(req,res)=>{const phone=normalizePhone(req.body.phone);if(!validE164(phone))return res.status(400).json({error:'Use international format, e.g. +233241234567'});try{const r=await sendOtp(phone);res.json({ok:true,message:'OTP sent',provider:r.provider,...(r.devOtp?{devOtp:r.devOtp}:{})})}catch(e){res.status(e.statusCode||502).json({error:'Could not send OTP'})}});
app.post('/api/auth/verify-otp',authLimiter,async(req,res)=>{const phone=normalizePhone(req.body.phone),code=String(req.body.code||'').trim();if(!validE164(phone)||!/^[0-9]{4,10}$/.test(code))return res.status(400).json({error:'Invalid phone or OTP'});try{const c=await verifyOtp(phone,code);if(c.status!=='approved')return res.status(400).json({error:'Incorrect or expired OTP'});const user=await upsertUser(phone);const token=jwt.sign({phone:user.phone,role:user.role||'customer',verified:true},SIGNING_SECRET,{expiresIn:'7d'});res.json({ok:true,token,user})}catch(e){res.status(502).json({error:'Could not verify OTP'})}});
app.get('/api/me',auth,async(req,res)=>res.json({user:await getUser(req.user.phone)||req.user}));
function makeId(p){return p+Math.floor(10000+Math.random()*90000)}
app.post('/api/orders',auth,async(req,res)=>{const id=makeId('OBU-'),o={id,customer_phone:req.user.phone,vendor:req.body.vendor||'Obuasi Kitchen',items:req.body.items||[],total:Number(req.body.total||0),status:'PAYMENT PENDING',created_at:new Date().toISOString(),pickup_code:'4821',delivery_pin:'7392'};if(pool){await q('insert into orders(id,customer_phone,vendor,items,total,status,pickup_code,delivery_pin) values($1,$2,$3,$4,$5,$6,$7,$8)',[o.id,o.customer_phone,o.vendor,JSON.stringify(o.items),o.total,o.status,o.pickup_code,o.delivery_pin]);}else memory.orders.set(id,o);await audit(req.user.phone,'order.created','order',id,{total:o.total});res.status(201).json(o)});
app.get('/api/orders',auth,async(req,res)=>{if(pool)return res.json(await q('select * from orders where customer_phone=$1 order by created_at desc',[req.user.phone]));res.json([...memory.orders.values()].filter(x=>x.customer_phone===req.user.phone))});
app.patch('/api/orders/:id/status',auth,async(req,res)=>{const s=String(req.body.status||'').slice(0,40);const allowed=['PAYMENT PENDING','Order created','Payment confirmed','Restaurant accepted','Preparing','Food ready','Rider assigned','Rider accepted','Rider arrived','Food picked up','Going to customer','Arrived at customer','Customer PIN verified','Completed'];if(!allowed.includes(s))return res.status(400).json({error:'Invalid order status'});if(pool){const existing=(await q('select * from orders where id=$1',[req.params.id]))[0];if(!existing)return res.status(404).json({error:'Order not found'});const canCustomer=existing.customer_phone===req.user.phone;const canRider=existing.rider_phone===req.user.phone&&['rider'].includes(req.user.role);const canOps=['vendor','admin','superadmin'].includes(req.user.role);if(!canCustomer&&!canRider&&!canOps)return res.status(403).json({error:'Not allowed to update this order'});const r=await q('update orders set status=$1,updated_at=now(),rider_phone=coalesce($2,rider_phone) where id=$3 returning *',[s,canRider?req.user.phone:req.body.riderPhone||null,req.params.id]);await audit(req.user.phone,'order.status','order',req.params.id,{status:s});return res.json(r[0])}const o=memory.orders.get(req.params.id);if(!o)return res.status(404).json({error:'Order not found'});if(o.customer_phone!==req.user.phone&&!['vendor','rider','admin','superadmin'].includes(req.user.role))return res.status(403).json({error:'Not allowed'});o.status=s;o.updated_at=new Date().toISOString();if(req.user.role==='rider')o.rider_phone=req.user.phone;res.json(o)});
app.post('/api/bookings',auth,async(req,res)=>{const id=makeId('OBU-HL-'),b={id,customer_phone:req.user.phone,hotel:req.body.hotel||'Obuasi Royal Hotel',room:req.body.room||'Executive Room',total:Number(req.body.total||450),status:'BOOKED',created_at:new Date().toISOString()};if(pool)await q('insert into bookings(id,customer_phone,hotel,room,total,status) values($1,$2,$3,$4,$5,$6)',[id,b.customer_phone,b.hotel,b.room,b.total,b.status]);else memory.bookings.set(id,b);await audit(req.user.phone,'booking.created','booking',id);res.status(201).json(b)});
app.get('/api/bookings',auth,async(req,res)=>{if(pool)return res.json(await q('select * from bookings where customer_phone=$1 order by created_at desc',[req.user.phone]));res.json([...memory.bookings.values()].filter(x=>x.customer_phone===req.user.phone))});
app.patch('/api/bookings/:id/status',auth,async(req,res)=>{const s=String(req.body.status||'').slice(0,40);if(!['BOOKED','CHECKED IN','CHECKED OUT','CANCELLED'].includes(s))return res.status(400).json({error:'Invalid booking status'});if(pool){const existing=(await q('select * from bookings where id=$1',[req.params.id]))[0];if(!existing)return res.status(404).json({error:'Booking not found'});if(existing.customer_phone!==req.user.phone&&!['hotel','admin','superadmin'].includes(req.user.role))return res.status(403).json({error:'Not allowed'});const r=await q('update bookings set status=$1,updated_at=now() where id=$2 returning *',[s,req.params.id]);await audit(req.user.phone,'booking.status','booking',req.params.id,{status:s});return res.json(r[0])}const b=memory.bookings.get(req.params.id);if(!b)return res.status(404).json({error:'Booking not found'});if(b.customer_phone!==req.user.phone&&!['hotel','admin','superadmin'].includes(req.user.role))return res.status(403).json({error:'Not allowed'});b.status=s;res.json(b)});
async function flw(pathname,body){const r=await fetch('https://api.flutterwave.com/v3'+pathname,{method:'POST',headers:{Authorization:'Bearer '+process.env.FLW_SECRET_KEY,'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.message||'Flutterwave error');return d}
app.post('/api/payments/checkout',auth,async(req,res)=>{if(!process.env.FLW_SECRET_KEY)return res.status(503).json({error:'Flutterwave is not configured'});const amount=Number(req.body.amount);if(!(amount>0))return res.status(400).json({error:'Invalid amount'});const tx_ref='OBG-'+Date.now()+'-'+crypto.randomBytes(3).toString('hex');const base=process.env.APP_URL||`${req.protocol}://${req.get('host')}`;try{const d=await flw('/payments',{tx_ref,amount,currency:'GHS',redirect_url:`${base}/payment-return`,customer:{email:req.body.email||`${req.user.phone.replace('+','')}@obuasigo.app`,name:req.body.name||'ObuasiGo Customer',phonenumber:req.user.phone},payment_options:'card,ghanamobilemoney',customizations:{title:'ObuasiGo',description:req.body.description||'ObuasiGo order payment'},meta:{entity_type:req.body.entityType||'order',entity_id:req.body.entityId||''}});if(pool)await q('insert into payments(tx_ref,user_phone,entity_type,entity_id,amount,currency,status) values($1,$2,$3,$4,$5,$6,$7)',[tx_ref,req.user.phone,req.body.entityType||'order',req.body.entityId||'',amount,'GHS','pending']);else memory.payments.set(tx_ref,{tx_ref,user_phone:req.user.phone,amount,status:'pending'});res.json({ok:true,tx_ref,link:d.data?.link})}catch(e){res.status(502).json({error:e.message})}});
app.get('/api/payments/verify/:transactionId',auth,async(req,res)=>{if(!process.env.FLW_SECRET_KEY)return res.status(503).json({error:'Flutterwave is not configured'});try{const r=await fetch(`https://api.flutterwave.com/v3/transactions/${encodeURIComponent(req.params.transactionId)}/verify`,{headers:{Authorization:'Bearer '+process.env.FLW_SECRET_KEY}});const d=await r.json();res.status(r.ok?200:502).json(d)}catch(e){res.status(502).json({error:e.message})}});
app.post('/api/webhooks/flutterwave',express.raw({type:'application/json'}),async(req,res)=>{const hash=req.headers['verif-hash'];if(!process.env.FLW_SECRET_HASH||hash!==process.env.FLW_SECRET_HASH)return res.status(401).end();let body;try{body=JSON.parse(req.body.toString())}catch{return res.status(400).end()}const tx=body.data||body;const ref=tx.tx_ref;if(ref){if(pool)await q('update payments set status=$1,transaction_id=$2 where tx_ref=$3',[tx.status||'completed',String(tx.id||''),ref]);else if(memory.payments.has(ref))memory.payments.get(ref).status=tx.status||'completed'}res.json({ok:true})});
app.post('/api/tracking/:orderId',auth,async(req,res)=>{if(req.user.role!=='rider')return res.status(403).json({error:'Rider access required'});const lat=Number(req.body.lat),lng=Number(req.body.lng),accuracy=Number(req.body.accuracy||0);if(!Number.isFinite(lat)||!Number.isFinite(lng))return res.status(400).json({error:'Invalid coordinates'});const p={orderId:req.params.orderId,lat,lng,accuracy,at:new Date().toISOString()};if(pool)await q('insert into tracking_points(order_id,lat,lng,accuracy) values($1,$2,$3,$4)',[p.orderId,lat,lng,accuracy]);else memory.tracking.set(p.orderId,p);broadcast(p.orderId,{type:'location',...p});res.json({ok:true,p})});
const sockets=new Map();let WebSocket;try{WebSocket=require('ws')}catch{}function broadcast(orderId,msg){for(const ws of sockets.get(orderId)||[])if(ws.readyState===1)ws.send(JSON.stringify(msg))}
const httpServer=require('http').createServer(app);if(WebSocket){const wss=new WebSocket.Server({server:httpServer,path:'/ws'});wss.on('connection',(ws,req)=>{const u=new URL(req.url,'http://localhost');const orderId=u.searchParams.get('orderId'),token=u.searchParams.get('token');let claims;try{claims=jwt.verify(token||'',SIGNING_SECRET)}catch{return ws.close(1008,'Unauthorized')}if(!orderId)return ws.close(1008,'Order required');if(!sockets.has(orderId))sockets.set(orderId,new Set());sockets.get(orderId).add(ws);ws.on('close',()=>sockets.get(orderId)?.delete(ws));ws.send(JSON.stringify({type:'connected',orderId}))})}
const vapidReady=!!(process.env.VAPID_PUBLIC_KEY&&process.env.VAPID_PRIVATE_KEY&&process.env.VAPID_SUBJECT);if(vapidReady)webpush.setVapidDetails(process.env.VAPID_SUBJECT,process.env.VAPID_PUBLIC_KEY,process.env.VAPID_PRIVATE_KEY);
app.get('/api/push/public-key',(req,res)=>res.json({configured:vapidReady,publicKey:vapidReady?process.env.VAPID_PUBLIC_KEY:null}));app.post('/api/push/subscribe',auth,async(req,res)=>{if(!vapidReady)return res.status(503).json({error:'Push not configured'});const sub=req.body.subscription;if(!sub?.endpoint)return res.status(400).json({error:'Invalid subscription'});if(pool)await q('insert into push_subscriptions(user_phone,endpoint,subscription) values($1,$2,$3) on conflict(endpoint) do update set subscription=$3,user_phone=$1',[req.user.phone,sub.endpoint,JSON.stringify(sub)]);else memory.push.set(sub.endpoint,{phone:req.user.phone,subscription:sub});res.json({ok:true})});
app.post('/api/push/send',auth,admin,async(req,res)=>{if(!vapidReady)return res.status(503).json({error:'Push not configured'});let subs=pool?await q('select * from push_subscriptions where user_phone=$1',[req.body.phone]):[...memory.push.values()].filter(x=>x.phone===req.body.phone);for(const s of subs){const sub=s.subscription||s;try{await webpush.sendNotification(sub,JSON.stringify({title:req.body.title||'ObuasiGo',body:req.body.body||'You have an update'}))}catch(e){console.error('push',e.message)}}res.json({ok:true})});
app.post('/api/documents',auth,upload.single('document'),async(req,res)=>{if(!req.file)return res.status(400).json({error:'Document file required'});const allowed=['image/jpeg','image/png','application/pdf'];if(!allowed.includes(req.file.mimetype))return res.status(400).json({error:'Only JPG, PNG or PDF allowed'});let url=null;if(process.env.SUPABASE_URL&&process.env.SUPABASE_SERVICE_ROLE_KEY&&process.env.SUPABASE_STORAGE_BUCKET){const {createClient}=require('@supabase/supabase-js');const sb=createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY);const filePath=`documents/${req.user.phone.replace(/\W/g,'_')}/${Date.now()}-${req.file.originalname.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const up=await sb.storage.from(process.env.SUPABASE_STORAGE_BUCKET).upload(filePath,req.file.buffer,{contentType:req.file.mimetype,upsert:false});if(up.error)return res.status(502).json({error:'Document storage failed'});url=up.data.path}const type=String(req.body.type||'identity').slice(0,40);if(!['identity','ghana_card','driver_license','vehicle','selfie','business_registration','hotel_license'].includes(type))return res.status(400).json({error:'Invalid document type'});if(pool){const r=await q('insert into documents(user_phone,doc_type,file_url) values($1,$2,$3) returning *',[req.user.phone,type,url]);return res.status(201).json(r[0])}const d={id:crypto.randomUUID(),user_phone:req.user.phone,doc_type:type,file_url:url,status:'pending'};memory.documents.set(d.id,d);res.status(201).json(d)});
app.get('/api/admin/overview',auth,admin,async(req,res)=>{if(pool){const [[customers],[riders],[vendors],[hotels],[orders],[bookings],[pending]] = await Promise.all([q("select count(*) n from users where role='customer'"),q("select count(*) n from users where role='rider'"),q("select count(*) n from users where role='vendor'"),q("select count(*) n from users where role='hotel'"),q('select count(*) n from orders'),q('select count(*) n from bookings'),q("select count(*) n from documents where status='pending'")]);return res.json({customers:+customers[0].n,riders:+riders[0].n,vendors:+vendors[0].n,hotels:+hotels[0].n,orders:+orders[0].n,bookings:+bookings[0].n,pendingDocuments:+pending[0].n})}res.json({customers:memory.users.size,riders:0,vendors:0,hotels:0,orders:memory.orders.size,bookings:memory.bookings.size,pendingDocuments:memory.documents.size})});
app.get('/api/admin/documents',auth,admin,async(req,res)=>res.json(pool?await q("select * from documents where status='pending' order by created_at asc"):Array.from(memory.documents.values()).filter(x=>x.status==='pending')));
app.patch('/api/admin/documents/:id',auth,admin,async(req,res)=>{if(pool){const r=await q('update documents set status=$1 where id=$2 returning *',[req.body.status,req.params.id]);if(!r[0])return res.status(404).json({error:'Document not found'});return res.json(r[0])}const d=memory.documents.get(req.params.id);if(!d)return res.status(404).json({error:'Document not found'});d.status=req.body.status;res.json(d)});
app.get('/payment-return',(req,res)=>res.sendFile(path.join(__dirname,'public','payment-return.html')));
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
initDb().then(()=>httpServer.listen(PORT,()=>console.log(`ObuasiGo running on ${PORT}`))).catch(e=>{console.error('DB init failed',e);process.exit(1)});
